### PR TITLE
Provide opt-out for crash reporting and device capture features

### LINKED ISSUE #68: Allow to opt-out collecting crashes
We should give more controls to users. It should be done through meta-data because we are providing automated initialization.

### PR DESCRIPTION
**Pull request by jmatsu**
Close #68

We should provide flexible configuration for users. Especially, opting-out data collection is getting important. Some of features are triggered by our client app, so SDK state must be delivered to our app through AIDL; We can know the active features from *init* event.

### CODE REVIEW

File: sdk/src/main/java/com/deploygate/sdk/DeployGate.java [hunk 1]
```diff
@@ -102,7 +102,7 @@ public void onEvent(
             } else if (DeployGateEvent.ACTION_ONESHOT_LOGCAT.equals(action)) {
                 String captureId = null;
 
-                if (mDeployGateClient.isSupported(Compatibility.DEVICE_CAPTURE)) {
+                if (mHostApp.canUseDeviceCapture() && mDeployGateClient.isSupported(Compatibility.DEVICE_CAPTURE)) {
```
Comment (jmatsu) [inline sdk/src/main/java/com/deploygate/sdk/DeployGate.java:105]: SDK cannot turn off the device capture feature completely because triggers will be fired from the client app.

File: sdk/src/test/java/com/deploygate/sdk/HostAppTest.java [hunk 2]
```diff
@@ -26,22 +26,63 @@ public void setUp() {
...
+                context,
+                new DeployGateSdkConfiguration.Builder().build()
+        );
 
-        Truth.assertThat(app.debuggable).isTrue();
         Truth.assertThat(app.canUseLogcat).isTrue();
         Truth.assertThat(app.packageName).isEqualTo("com.deploygate.sdk.test");
         Truth.assertThat(app.sdkVersion).isEqualTo(4);
         Truth.assertThat(app.sdkArtifactVersion).isEqualTo("4.6.1");
+        Truth.assertThat(app.activeFeatureFlags).isEqualTo(31);
```
Comment (satsukies) [inline sdk/src/test/java/com/deploygate/sdk/HostAppTest.java:38]: I understood this assertion expected `31` because  activeFeatureFlags has 0x11111 -> 31 when all features enabled.

**Review by satsukies — APPROVED** [review]
LGTM 👍

**Comment by jmatsu** [comment]
Thank you~ 🙏
